`timescale 1ns/1ps

// Standalone NPU test.  The SRAM image and expected output are generated by
// tools/export_model.py from the PyTorch INT8 checkpoint.
module tb_cnn_npu #(
  parameter integer LANES=16,
  parameter integer SRAM_BYTES=16*1024,
  parameter integer DESC_BASE=12*1024,
  parameter integer OUTPUT_BASE=8*1024,
  parameter MEM_FILE="cnn_npu_int8/generated/16k/cnn_npu_mem.hex"
);
  `include "generated/16k/golden.svh"

  logic clk=1'b0;
  logic rst_ni=1'b0;
  logic ena=1'b0;
  logic wea=1'b0;
  logic [3:0] be=4'hf;
  logic [13:0] addra=14'd0;
  logic [31:0] dina=32'd0;
  logic [31:0] douta;
  logic irq;

  localparam logic [13:0] LOCAL_BASE_WORD = 14'h1000;
  cnn_npu_top #(
      .LANES(LANES),
      .SRAM_BYTES(SRAM_BYTES),
      .MAX_LAYERS(8),
      .MEM_INIT_FILE(MEM_FILE)
  ) dut (
      .clka(clk), .rst_ni(rst_ni), .ena(ena), .wea(wea), .be_i(be),
      .addra(addra), .dina(dina), .douta(douta), .irq_o(irq)
  );

  always #5 clk = ~clk;

  task automatic bus_write(input [13:0] word_addr, input [31:0] data);
    begin
      @(negedge clk);
      ena=1'b1; wea=1'b1; addra=word_addr; dina=data; be=4'hf;
      @(posedge clk);
      @(negedge clk);
      ena=1'b0; wea=1'b0; addra=14'd0; dina=32'd0;
    end
  endtask

  task automatic bus_read(input [13:0] word_addr, output [31:0] data);
    begin
      @(negedge clk);
      ena=1'b1; wea=1'b0; addra=word_addr;
      @(posedge clk);
      #1 data=douta;
      @(negedge clk);
      ena=1'b0; addra=14'd0;
    end
  endtask

  logic [31:0] status;
  logic [31:0] word_value;
  integer polls;
  integer i;
  integer errors;
  integer byte_addr;
  integer word_addr;
  integer byte_lane;
  integer got;
  integer max_hw;
  integer max_ref;
  integer arg_hw;
  integer arg_ref;
  integer ref_i;
  integer max_abs_diff;

  initial begin
    $dumpfile("cnn_npu.vcd");
    $dumpvars(0, tb_cnn_npu);
    repeat (4) @(posedge clk);
    rst_ni=1'b1;
    repeat (2) @(posedge clk);

    // descriptor base is a byte offset in the local SRAM.
    bus_write(14'd4, DESC_BASE);
    bus_write(14'd5, 32'd6);
    bus_write(14'd0, 32'd1);

    status=0; polls=0;
    while (((status & 32'h2)==0) && (polls<200000)) begin
      bus_read(14'd1, status);
      polls=polls+1;
    end
    if ((status & 32'h2)==0) begin
      $display("[CNN] FAIL timeout status=%h cycles=%0d", status, polls);
      $finish;
    end

    errors=0;
    max_hw=-1; max_ref=-1; arg_hw=-1; arg_ref=-1; max_abs_diff=0;
    for (i=0; i<10; i=i+1) begin
      byte_addr=OUTPUT_BASE+i;
      word_addr=LOCAL_BASE_WORD+(byte_addr/4);
      byte_lane=byte_addr%4;
      bus_read(word_addr, word_value);
      got=(word_value >> (8*byte_lane)) & 8'hff;
      ref_i=golden_output(i);
      if (((got > ref_i) ? (got-ref_i) : (ref_i-got)) > max_abs_diff)
        max_abs_diff=((got > ref_i) ? (got-ref_i) : (ref_i-got));
      if (((got > ref_i) ? (got-ref_i) : (ref_i-got)) > 1) begin
        $display("[CNN] MISMATCH output[%0d] hw=%0d pytorch=%0d", i, got, ref_i);
        errors=errors+1;
      end
      if (got > max_hw) begin max_hw=got; arg_hw=i; end
      if ((i==0) || (ref_i > max_ref)) begin max_ref=ref_i; arg_ref=i; end
    end
    if (arg_hw != arg_ref) begin
      $display("[CNN] ARGMAX MISMATCH hw=%0d pytorch=%0d", arg_hw, arg_ref);
      errors=errors+1;
    end
    if (errors==0)
      $display("[CNN] PASS: PyTorch golden matched within +/-1 (max diff=%0d, argmax=%0d, %0d polls)", max_abs_diff, arg_hw, polls);
    else
      $display("[CNN] FAIL: %0d mismatches", errors);
    $finish;
  end
endmodule
